# Generated by Django 4.1 on 2022-09-11 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpennodeCharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_id', models.CharField(max_length=64)),
                ('order_id', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('created_at', models.DateTimeField()),
                ('status', models.CharField(max_length=16)),
                ('amount', models.IntegerField()),
                ('currency', models.CharField(blank=True, max_length=3, null=True)),
                ('source_fiat_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('auto_settle', models.BooleanField()),
                ('callback_url', models.CharField(blank=True, max_length=256, null=True)),
                ('success_url', models.CharField(blank=True, max_length=256, null=True)),
                ('hosted_checkout_url', models.CharField(blank=True, max_length=256, null=True)),
                ('notif_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=256, null=True)),
                ('metadata', models.TextField(blank=True, null=True)),
                ('chain_invoice', models.TextField(blank=True, null=True)),
                ('uri', models.CharField(blank=True, max_length=512, null=True)),
                ('ttl', models.IntegerField(blank=True, null=True)),
                ('lightning_invoice', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OpennodeChargeEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField()),
                ('status', models.CharField(max_length=16)),
                ('data', models.TextField()),
                ('charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='opennode.opennodecharge')),
            ],
        ),
    ]
